# Importing Libraries

In [6]:
import numpy as np
import pandas as pd

## Importing Dataset

In [7]:
dataset = pd.read_csv('data.csv')

In [8]:
dataset

R&D Spend  Administration  Marketing Spend       State  Profit
0       85941          137189            70300       Texas   70987
1      124551          143478            70518    Illinois  204390
2       83527          107719            79448    New York  126451
3      143901           94550            52582       Texas  136014
4       86072           80807           163165  California   37206
5       57438           70221           185157    New York  145789
6      189345          106830           106282    Illinois  297169
7       58722           49418            34875       Texas   80765
8      108089           79145           214682    Illinois   67661
9       89042          122782           166056     Florida   15086
10     123511          133866           218950    Illinois  136123
11     104051          133233            55858       Texas   95815
12      65923          130847           139684     Florida  242716
13     185257          107691           121845     Florida  175873
14      76471          102252           171772    New York  190562
15      54025          126107            96589  California  274500
16     156593           43793           198653    New York   10307
17     129491           85733            66910    Illinois  161973
18      79364          108257            34820  California  181603
19     149135          116203            31661    Illinois  284640
20     197555           95466           236412    Illinois  185630
21     106132           83461           126186    New York  199164
22     143238           92871           118678     Florida  234980
23     171442          128879           112305    New York  135405
24     113899           58160            71316    Illinois  209227
25      68897          106994           236330     Florida  264187
26     192113          110818           165977       Texas   41671
27      59506           40502           228016    New York  125371
28     142650          122425           116429  California  259043
29     118572           99958           192972    New York  152640
30     128246          140665           195320  California  141976
31     105717          131141            31975    Illinois   83261
32      52155           42442            35393       Texas  289945
33      67411          113873           134865       Texas  169050
34      57421           50619           225079       Texas  271125
35     142985           51640            55564    Illinois  169888
36     167503           89891            78391    Illinois  111413
37     169782           50078           127235     Florida   40637
38     112304          101173           114142    New York  125171
39     188546           73645            93130    New York  161418
40     195457          132661           174579  California   33545
41      64238           92877           204184  California   58620
42     126050          149749           166835    New York  160397
43      70543           57875            92112       Texas   22844
44     140147           75686           115419  California  135801
45     150090           47777           118335    New York   74409
46     141538          143529            60590     Florida  160972
47     144858           82877           134929  California  202677
48      94646          140321            31590    New York  135750
49      50268           75671           189191     Florida   45767

In [9]:
x = dataset.iloc[:,:-1].values

In [10]:
y = dataset.iloc[:,-1].values

In [11]:
x

array([[85941, 137189, 70300, 'Texas'],
       [124551, 143478, 70518, 'Illinois'],
       [83527, 107719, 79448, 'New York'],
       [143901, 94550, 52582, 'Texas'],
       [86072, 80807, 163165, 'California'],
       [57438, 70221, 185157, 'New York'],
       [189345, 106830, 106282, 'Illinois'],
       [58722, 49418, 34875, 'Texas'],
       [108089, 79145, 214682, 'Illinois'],
       [89042, 122782, 166056, 'Florida'],
       [123511, 133866, 218950, 'Illinois'],
       [104051, 133233, 55858, 'Texas'],
       [65923, 130847, 139684, 'Florida'],
       [185257, 107691, 121845, 'Florida'],
       [76471, 102252, 171772, 'New York'],
       [54025, 126107, 96589, 'California'],
       [156593, 43793, 198653, 'New York'],
       [129491, 85733, 66910, 'Illinois'],
       [79364, 108257, 34820, 'California'],
       [149135, 116203, 31661, 'Illinois'],
       [197555, 95466, 236412, 'Illinois'],
       [106132, 83461, 126186, 'New York'],
       [143238, 92871, 118678, 'Florida'],
     

In [12]:
y

array([ 70987, 204390, 126451, 136014,  37206, 145789, 297169,  80765,
        67661,  15086, 136123,  95815, 242716, 175873, 190562, 274500,
        10307, 161973, 181603, 284640, 185630, 199164, 234980, 135405,
       209227, 264187,  41671, 125371, 259043, 152640, 141976,  83261,
       289945, 169050, 271125, 169888, 111413,  40637, 125171, 161418,
        33545,  58620, 160397,  22844, 135801,  74409, 160972, 202677,
       135750,  45767])

## Encoding Categorial Data

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[3])],remainder = 'passthrough')

In [17]:
x = np.array(ct.fit_transform(x))

In [16]:
x

array([[85941, 137189, 70300, 'Texas'],
       [124551, 143478, 70518, 'Illinois'],
       [83527, 107719, 79448, 'New York'],
       [143901, 94550, 52582, 'Texas'],
       [86072, 80807, 163165, 'California'],
       [57438, 70221, 185157, 'New York'],
       [189345, 106830, 106282, 'Illinois'],
       [58722, 49418, 34875, 'Texas'],
       [108089, 79145, 214682, 'Illinois'],
       [89042, 122782, 166056, 'Florida'],
       [123511, 133866, 218950, 'Illinois'],
       [104051, 133233, 55858, 'Texas'],
       [65923, 130847, 139684, 'Florida'],
       [185257, 107691, 121845, 'Florida'],
       [76471, 102252, 171772, 'New York'],
       [54025, 126107, 96589, 'California'],
       [156593, 43793, 198653, 'New York'],
       [129491, 85733, 66910, 'Illinois'],
       [79364, 108257, 34820, 'California'],
       [149135, 116203, 31661, 'Illinois'],
       [197555, 95466, 236412, 'Illinois'],
       [106132, 83461, 126186, 'New York'],
       [143238, 92871, 118678, 'Florida'],
     

## Split The Data

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [22]:
x_train

array([[0.0, 1.0, 0.0, 0.0, 0.0, 65923, 130847, 139684],
       [1.0, 0.0, 0.0, 0.0, 0.0, 86072, 80807, 163165],
       [0.0, 1.0, 0.0, 0.0, 0.0, 169782, 50078, 127235],
       [0.0, 0.0, 1.0, 0.0, 0.0, 108089, 79145, 214682],
       [0.0, 0.0, 0.0, 0.0, 1.0, 143901, 94550, 52582],
       [0.0, 0.0, 1.0, 0.0, 0.0, 189345, 106830, 106282],
       [1.0, 0.0, 0.0, 0.0, 0.0, 64238, 92877, 204184],
       [0.0, 1.0, 0.0, 0.0, 0.0, 141538, 143529, 60590],
       [1.0, 0.0, 0.0, 0.0, 0.0, 144858, 82877, 134929],
       [1.0, 0.0, 0.0, 0.0, 0.0, 54025, 126107, 96589],
       [0.0, 1.0, 0.0, 0.0, 0.0, 89042, 122782, 166056],
       [0.0, 0.0, 0.0, 1.0, 0.0, 156593, 43793, 198653],
       [0.0, 0.0, 1.0, 0.0, 0.0, 113899, 58160, 71316],
       [0.0, 0.0, 0.0, 0.0, 1.0, 57421, 50619, 225079],
       [0.0, 0.0, 1.0, 0.0, 0.0, 105717, 131141, 31975],
       [0.0, 0.0, 0.0, 0.0, 1.0, 85941, 137189, 70300],
       [1.0, 0.0, 0.0, 0.0, 0.0, 140147, 75686, 115419],
       [0.0, 0.0, 0.0, 1.0, 0.0, 5950

In [23]:
y_train

array([242716,  37206,  40637,  67661, 136014, 297169,  58620, 160972,
       202677, 274500,  15086,  10307, 209227, 271125,  83261,  70987,
       135801, 125371, 169050, 145789, 152640,  95815, 111413, 204390,
       199164, 126451,  22844, 169888, 135405,  33545, 136123, 234980,
       181603,  45767, 185630,  80765, 160397, 190562, 259043, 125171])

In [24]:
len(y_train)

40

In [25]:
len(y_test)

10

## Model

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
reg = LinearRegression()

In [28]:
reg.fit(x_train,y_train)

LinearRegression()

## Predict

In [29]:
y_pred = reg.predict(x_test)

In [30]:
y_pred

array([118993.58672135, 128929.47040751, 153381.41063944, 119788.08081408,
       165236.44697064, 171917.78994398, 109145.18136692, 117054.3223732 ,
       112386.15412587, 179301.74550624])

In [31]:
y_test

array([175873, 161418, 141976,  74409, 161973, 135750,  41671, 264187,
       289945, 284640])

In [32]:
np.set_printoptions(precision = 2)

In [34]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[118993.59 175873.  ]
 [128929.47 161418.  ]
 [153381.41 141976.  ]
 [119788.08  74409.  ]
 [165236.45 161973.  ]
 [171917.79 135750.  ]
 [109145.18  41671.  ]
 [117054.32 264187.  ]
 [112386.15 289945.  ]
 [179301.75 284640.  ]]


In [35]:
#polynomial regression
#support vector regression
#Decision treee Regression
#Random Forest Regression