# Importing Libraries

In [2]:
import numpy as np
import pandas as pd

## Importing Dataset

In [3]:
dataset = pd.read_excel('Data4.xlsx')

In [4]:
dataset

Age  Estimated Salary  Purchased
0     45            113807          0
1     54             63434          0
2     44             99724          0
3     43            105697          0
4     32             58732          0
..   ...               ...        ...
395   23             54160          0
396   59            115595          1
397   23            109111          1
398   44             94929          0
399   22            103506          0

[400 rows x 3 columns]

In [5]:
x = dataset.iloc[:,:-1].values

In [6]:
x

array([[    45, 113807],
       [    54,  63434],
       [    44,  99724],
       [    43, 105697],
       [    32,  58732],
       [    26,  41314],
       [    55,  53954],
       [    39,  87108],
       [    20, 117044],
       [    27, 117505],
       [    35,  66668],
       [    33,  53061],
       [    31, 109252],
       [    42,  69749],
       [    34,  46907],
       [    47,  48777],
       [    53,  81745],
       [    21, 111818],
       [    51,  53624],
       [    42,  53321],
       [    41,  40488],
       [    44,  52574],
       [    41,  35240],
       [    41,  73221],
       [    25,  40478],
       [    34,  85645],
       [    56,  49262],
       [    52,  82796],
       [    27,  34432],
       [    24,  94291],
       [    58, 109104],
       [    23,  89399],
       [    25, 109714],
       [    51,  80428],
       [    49, 117731],
       [    54,  30302],
       [    59, 112558],
       [    35,  30055],
       [    32,  38717],
       [    49,  58699],


In [7]:
y = dataset.iloc[:,-1].values

In [8]:
y

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,

## Split Dataset

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [11]:
len(x_train)

300

In [12]:
len(x_test)

100

## Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()

In [15]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [16]:
x_train

array([[-1.34465231e-01, -1.44856412e+00],
       [-7.40424425e-01, -1.35958060e+00],
       [ 3.86659676e-02, -1.27509482e+00],
       [-3.07596429e-01, -6.96613030e-02],
       [-4.78996315e-02,  1.51311562e+00],
       [-1.08668682e+00,  1.13120250e+00],
       [ 1.07745316e+00,  1.01685165e+00],
       [ 8.17756360e-01,  5.05619170e-01],
       [-7.40424425e-01, -1.53542471e+00],
       [ 8.17756360e-01, -8.90842874e-01],
       [-3.94162028e-01, -1.52596144e+00],
       [ 9.04321959e-01,  1.14023399e+00],
       [-1.34638362e+00,  3.29559165e-01],
       [ 3.84928364e-01, -7.71454544e-01],
       [-4.80727627e-01, -2.16395965e-01],
       [-1.43294922e+00,  1.56424606e+00],
       [ 2.11797166e-01, -1.11598235e+00],
       [-7.40424425e-01,  1.39696567e+00],
       [ 3.84928364e-01,  7.85486211e-02],
       [ 1.16401876e+00,  1.13364928e+00],
       [ 9.90887559e-01, -1.44654913e+00],
       [-9.13555623e-01, -1.24382645e+00],
       [-1.69264602e+00, -8.99010791e-01],
       [-1.

## SVM Model

In [19]:
from sklearn.svm import SVC

In [34]:
classifier = SVC(kernel = 'linear',random_state = 0)

In [35]:
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

## Prediction

In [36]:
print(classifier.predict(sc.transform([[32,150000]]))[0])

1


In [37]:
print(classifier.predict(sc.transform([[20,86000]]))[0])

1


In [38]:
y_pred = classifier.predict(x_test)

In [39]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]]


## Confusion Matrix and Accuracy

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [42]:
cm = confusion_matrix(y_test,y_pred)

In [43]:
cm

array([[ 0, 52],
       [ 0, 48]])

In [44]:
accuracy_score(y_test,y_pred)

0.48

In [ ]:
#LR
#SVM
#K-Nearest Neighbours(KNN)
#Kernel SVM
#Naive Bayes
#Decesion Tree Classification
#Random Forest Classification